### ISSUE TITLE
How to build the linux kernel

### ISSUE THREAD

**Issue by jiangwx** [Hosseinabady/ZynqDynamicEnergyManagemen#1]
Hi! I read your paper 'Run-time power gating in hybrid ARM-FPGA devices' in FPL2014 and it's very interesting! I'm trying to reproduce your work.
As shown in power_monitoring/src/power_monitor.c, the PMBus is mapped to i2c-8, however, the original power_monitor.c in Zynq7000AP_SoC_ZC702_pwr_monitor_design.zip,  the PMBus is mapped to i2c-9. So I'm wondering whether you have configed the device-tree or kernel.

**Comment by Hosseinabady** [comment]
yes, as I remember I had changed the devicetree many times for different purposes and I had my own version of devicetree. you should define the exact devices paths in the code based on your configuration.
